project:
  type: website
  output-dir: docs

website:
  title: "CARBONIQUE"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: Documentation/index.qmd
        text: Documentation
      # - href: FieldWorkProcedures.qmd
      #   text: Site Monitoring & Field Work
      - href: Data.qmd
        text: Field Sites & Data
      - href: OutreachNews.qmd
        text: Outreach and News
    right:
      - icon: github
        href: https://github.com/carboni-que
        aria-label: Quarto GitHub
  sidebar:
    - id: home
      title: "Home"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: index.qmd
          text: Home
        - href: Research.qmd
          text: Research
        - href: People.qmd
          text: People
        - href: Publications.qmd
          text: Publications
    - id: documentation
      title: "Documentation"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: Documentation/index.qmd
          text: Home
        - href: Documentation/DataWorkflows.qmd
          text: Data pipeline
        - href: Documentation/UsingGit.qmd
          text: Using Git
        - section: Site Monitoring & Field Work  
          contents:
          - href: Documentation/Fieldwork/DailyMonitoring.qmd
            text: Daily monitoring
          - href: Documentation/Fieldwork/FieldworkProcedures.qmd
            text: Fieldwork Protocols & Procedures
          - href: Documentation/Fieldwork/Calibration.qmd
            text: Calibration
          - href: Documentation/Fieldwork/Cleaning.qmd
            text: Cleaning
          - href: Documentation/Fieldwork/DataEntry.qmd
            text: Field Data Entry
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false

