project:
  type: website
  output-dir: docs

website:
  cookie-consent: true
  site-url: https://carboni-que.github.io
  #title: CARBONIQUE
  favicon: "images/logos/CQ-Logo-Icon-Color-BG@0.5x.png"
  navbar:
    logo: "images/logos/CQ-Logo-Long-Color@0.5x.png"
    left:
      - index.qmd
      - documentation.qmd
      - data.qmd
      - news.qmd

    right:
      - icon: github
        href: https://github.com/carboni-que
        aria-label: Carbonique GitHub
      - icon: box-arrow-in-right
        href: https://uqam.sharepoint.com/sites/CARBONIQUE?xsdata=MDV8MDJ8c2NobGFpcGZlci5tYXJ0aW5hQHVxYW0uY2F8YjIxOGYzZmNlNDA0NGI2YmZmZTEwOGRjZDY0ZWVhM2F8MTJjYjRlMWE0MmRhNDkxYzkwZTE3YTdhOTc1MzUwNmZ8MHwwfDYzODYyMDg4MTYzMzA1Nzg3M3xVbmtub3dufFRXRnBiR1pzYjNkOGV5SldJam9pTUM0d0xqQXdNREFpTENKUUlqb2lWMmx1TXpJaUxDSkJUaUk2SWsxaGFXd2lMQ0pYVkNJNk1uMD18MHx8fA%3d%3d&sdata=S2J4UXhkaWdyR1lKZEpGaE5MK3IyYnVMa2M5dlZ2QU05eUIxTHpZZGZ2ND0%3d
        aria-label: Login Sharepoint
  sidebar:
    - id: accueil
      title: "Accueil"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: index.qmd
          text: Accueil
        - href: research.qmd
          text: Recherche
        - href: people.qmd
          text: Équipe
        - href: join.qmd
          text: Rejoignez-nous
        # - href: Publications.qmd
        #   text: Publications
        - href: partners.qmd
          text: Partenaires
    - id: home
      title: "Home"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: index.qmd
          text: Home
        - href: research.qmd
          text: Research
        - href: people.qmd
          text: People
        # - href: Publications.qmd
        #   text: Publications
        - href: join.qmd
          text: Join us!
        - href: partners.qmd
          text: Partners

format:
  html:
    theme:
      - sandstone
      - custom.scss
    css: styles.css
    toc: true
    include-after-body:
    - text: |
        <script type="text/javascript">
        var elements = document.querySelectorAll('[aria-label]');

        for (var i = 0; i < elements.length; i++) {
          var ariaLabel = elements[i].getAttribute('aria-label');
          elements[i].setAttribute('data-bs-title', ariaLabel);
          elements[i].setAttribute('data-bs-toggle', 'tooltip');
        }
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
        </script>




babelquarto:
  languagecodes:
  - name: fr
    text: "Français"
  - name: en
    text: "English"
  mainlanguage: 'fr'
  languages: ['en']
#title-en: "CARBONIQUE"
description-en: description in en
author-en: author in en
lang: fr
